# Generated by Django 3.2.3 on 2021-05-20 10:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branch_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=django.contrib.postgres.indexes.GinIndex(fields=['branch_vector'], name='branches_branch__03c095_gin'),
        ),
    ]
